# enc28j60_eth.sdc -- timing constraints
#
# Without an explicit clock definition the Timing Analyzer reports
# "Timing requirements not met" purely for lack of a clock. Always present.

create_clock -name clk_50 -period 20.000 [get_ports {clk}]

derive_clock_uncertainty

# Async inputs -- no timing relationship to clk_50, both are synchronised
# in RTL before use.
set_false_path -from [get_ports {nrst}]  -to [all_registers]
set_false_path -from [get_ports {key[*]}] -to [all_registers]
set_false_path -from [get_ports {enc_int}] -to [all_registers]

# SPI is generated by an FSM off clk_50, not a dedicated output clock. At
# 12.5 MHz (M1) the round-trip margin is large; constrain the I/O loosely so
# the fitter still places the pins sensibly.
set_output_delay -clock clk_50 -max 5.0 [get_ports {enc_sck enc_mosi enc_cs_n enc_rst_n}]
set_output_delay -clock clk_50 -min 0.0 [get_ports {enc_sck enc_mosi enc_cs_n enc_rst_n}]
set_input_delay  -clock clk_50 -max 10.0 [get_ports {enc_miso}]
set_input_delay  -clock clk_50 -min 0.0  [get_ports {enc_miso}]

set_false_path -from [all_registers] -to [get_ports {led[*]}]
