# mkfont.ps1 -- rasterise ASCII 32..126 into a 5x8 column-major font for the
# SSD1306, and emit both a .mem file for $readmemh and an ASCII-art proof sheet
# so the result can be eyeballed rather than trusted.
#
# SSD1306 display RAM is column-major: one byte = 8 vertical pixels of a page,
# bit 0 at the top. A 5x8 glyph is therefore 5 bytes.

Add-Type -AssemblyName System.Drawing
$ErrorActionPreference = "Stop"

$W = 5; $H = 8
$outDir = "C:\BGE\AI\FPGA\ep4ce6e22-enc28j60-ethernet\rtl"
$mem    = Join-Path $outDir "font5x8.mem"
$proof  = "C:\Users\BGeorge\AppData\Local\Temp\claude\C--BGE-AI-FPGA-EP4CE6E22\e0ede4f5-77b2-40ae-af38-92f613855a46\scratchpad\font-proof.txt"

# Render into a taller cell then crop to the ink, so glyphs sit on a common
# baseline regardless of the font's own metrics.
$CW = 16; $CH = 20
$fontName = "Small Fonts"
try { $f = New-Object System.Drawing.Font($fontName, 9, [System.Drawing.FontStyle]::Regular, [System.Drawing.GraphicsUnit]::Pixel) }
catch { $fontName = "Consolas"; $f = New-Object System.Drawing.Font($fontName, 9, [System.Drawing.FontStyle]::Regular, [System.Drawing.GraphicsUnit]::Pixel) }

$glyphs = @{}
$inkRows = @{}

for ($c = 32; $c -le 126; $c++) {
    $bmp = New-Object System.Drawing.Bitmap($CW, $CH)
    $g   = [System.Drawing.Graphics]::FromImage($bmp)
    $g.Clear([System.Drawing.Color]::Black)
    $g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::SingleBitPerPixelGridFit
    $g.DrawString([char]$c, $f, [System.Drawing.Brushes]::White, 1, 1)
    $g.Dispose()

    # threshold into a bool grid
    $grid = New-Object 'bool[,]' $CW, $CH
    for ($x = 0; $x -lt $CW; $x++) {
        for ($y = 0; $y -lt $CH; $y++) {
            $grid[$x, $y] = ($bmp.GetPixel($x, $y).R -gt 110)
        }
    }
    $bmp.Dispose()
    $glyphs[$c] = $grid
}

# Find the global ink band so every glyph shares one baseline.
$minY = $CH; $maxY = -1
for ($c = 33; $c -le 126; $c++) {
    $grid = $glyphs[$c]
    for ($y = 0; $y -lt $CH; $y++) { for ($x = 0; $x -lt $CW; $x++) {
        if ($grid[$x,$y]) { if ($y -lt $minY) { $minY = $y }; if ($y -gt $maxY) { $maxY = $y } } } }
}
$bandH = $maxY - $minY + 1

$lines = @()
$art   = @("font: $fontName   ink band rows $minY..$maxY (height $bandH), cell ${W}x${H}")

for ($c = 32; $c -le 126; $c++) {
    $grid = $glyphs[$c]
    # horizontal ink extent for this glyph
    $minX = $CW; $maxX = -1
    for ($x = 0; $x -lt $CW; $x++) { for ($y = 0; $y -lt $CH; $y++) {
        if ($grid[$x,$y]) { if ($x -lt $minX) { $minX = $x }; if ($x -gt $maxX) { $maxX = $x } } } }
    if ($maxX -lt 0) { $minX = 0; $maxX = -1 }   # blank glyph (space)

    $cols = @()
    for ($i = 0; $i -lt $W; $i++) {
        $b = 0
        $sx = $minX + $i
        if ($sx -le $maxX) {
            # BAND_OFF lifts the crop so caps sit at rows 0..6 and the bottom
            # row is left for descenders (g j p q y). The ink band is taller
            # than the 8-row cell, so something must be sacrificed; clipping a
            # descender tail costs less legibility than clipping cap tops.
            for ($r = 0; $r -lt $H; $r++) {
                $sy = $minY + 1 + $r
                if ($sy -le $maxY -and $sx -lt $CW -and $sy -lt $CH) {
                    if ($grid[$sx, $sy]) { $b = $b -bor (1 -shl $r) }
                }
            }
        }
        $cols += $b
    }

    $lines += ("{0:x2} {1:x2} {2:x2} {3:x2} {4:x2}" -f $cols[0],$cols[1],$cols[2],$cols[3],$cols[4])

    # proof sheet
    $art += ""
    $art += ("--- 0x{0:x2} '{1}' ---" -f $c, [char]$c)
    for ($r = 0; $r -lt $H; $r++) {
        $row = ""
        for ($i = 0; $i -lt $W; $i++) { $row += $(if ($cols[$i] -band (1 -shl $r)) { "#" } else { "." }) }
        $art += $row
    }
}

$f.Dispose()

$hdr = @(
"// font5x8.mem -- ASCII 32..126, 5 bytes per glyph, column-major.",
"// Byte n is column n; bit 0 is the top pixel, matching SSD1306 page layout.",
"// Generated by tools/mkfont.ps1 -- regenerate rather than editing by hand."
)
Set-Content -Path $mem -Value ($hdr + $lines) -Encoding ascii
Set-Content -Path $proof -Value $art -Encoding ascii

"font       : $fontName"
"glyphs     : $(126-32+1)"
"bytes      : $((126-32+1)*$W)"
"ink band   : rows $minY..$maxY (height $bandH of $H)"
"mem file   : $mem"
"proof      : $proof"
